### ISSUE TITLE
Conformance Validation Issues

### ISSUE THREAD

**Issue by mythilymaran** [ConsumerDataStandardsAustralia/cds-client-java-cli#6]
I am working on conformance testing  via CDS Client Java CLI but facing few challenges on below items:

1)	Executing conformance testing on individual payloads locally by cloning the repository https://github.com/ConsumerDataStandardsAustralia/cds-client-java-cli. 

Noticed that validation output is different to what I have observed from the workshop demo. Do I need to enable logging info to get more detailed information?  
  
![Conformance_Validation_Output](https://user-images.githubusercontent.com/51734694/59729932-d006fa00-9283-11e9-9265-7412eb3590cc.png)

2)	In order to debug further on the exception, I started validating the Json with individual schemas(BankingProductBundle, BankingProductFee) and it passes the conformance testing whereas having them put together on the same file causing exception. Please confirm if I need to follow any other steps.

For instance, we validated below bundle object separately 

[
        {
            "name": "Mortgage Advantage Package",
            "description": "Add a Mortgage Advantage Package to your eligible home loan to access special discounts.",
            "additionalInfoUri": "https://www.com.au/home-loans/wealth-package-test.html",
            "productIds": [
                "8df91527a5774d7bb795eebe2509f941",
                "5f05d7f60e0040bfbc4f3a89c3181f5f"
            ]
        }
    ]
And you can see the test passed in the below screenshot

![Conformance_Validation_Bundle_Schema](https://user-images.githubusercontent.com/51734694/59730160-a69a9e00-9284-11e9-99a9-7c6d10f896c6.png)

But when we have this bundle info part of the product detailed json, we get exception on the additionalInfoUri field (PS: enabled logging on the source code for debugging purpose)

![Conformance_Validation_Bundle](https://user-images.githubusercontent.com/51734694/59730200-c9c54d80-9284-11e9-9920-d8927f63ae96.png)

Thanks for your support

**Comment by fyang1024** [comment]
Hi Mythily, I believe this issue has been addressed as I checked the email conversation. I'll close it now.
Thank you for your support
